
database:
  connection_string: "<inser your connection string according to postgresql documentation https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING>"

bot:
  host: tg
  token: "<insert your api key here>"
  # message is sent in response to /start
  start_message: "start"
  # message is sent in response to /help command
  help_message: "help"
  # message is sent in response to unsupported message
  fail_message: "in case of fail"
  # initial keyboard for all users
  init_keyboard: [100, 200, 300]
  # default picture (insert file_id that telegram provides)
  picture: "AgACAgIAAxkBAAIN72KZyXdBY_6me6-56geipv0za1p7AAKoujEbRanQSCGfZ_cEQWUzAQADAgADcwADJAQ"

plotter:
  # path to directory where temporarily store images
  temp_store: "."

logger:
  verbosity: info